-- Rollback user table extensions
DROP INDEX IF EXISTS idx_users_country_city;
DROP INDEX IF EXISTS idx_users_status;
DROP INDEX IF EXISTS idx_users_is_online;
DROP INDEX IF EXISTS idx_users_phone;
DROP INDEX IF EXISTS idx_users_username;

ALTER TABLE users DROP COLUMN IF EXISTS fingerprint;
ALTER TABLE users DROP COLUMN IF EXISTS coins;
ALTER TABLE users DROP COLUMN IF EXISTS status;
ALTER TABLE users DROP COLUMN IF EXISTS last_active_at;
ALTER TABLE users DROP COLUMN IF EXISTS is_online;
ALTER TABLE users DROP COLUMN IF EXISTS vip_expires_at;
ALTER TABLE users DROP COLUMN IF EXISTS is_vip;
ALTER TABLE users DROP COLUMN IF EXISTS language;
ALTER TABLE users DROP COLUMN IF EXISTS bio;
ALTER TABLE users DROP COLUMN IF EXISTS city;
ALTER TABLE users DROP COLUMN IF EXISTS country;
ALTER TABLE users DROP COLUMN IF EXISTS birthday;
ALTER TABLE users DROP COLUMN IF EXISTS gender;
ALTER TABLE users DROP COLUMN IF EXISTS avatar_url;
ALTER TABLE users DROP COLUMN IF EXISTS phone;
ALTER TABLE users DROP COLUMN IF EXISTS username;
