#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*)
        if command -v cygpath > /dev/null 2>&1; then
            basedir=`cygpath -w "$basedir"`
        fi
    ;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/home/ubuntu/.local/share/pnpm/global/5/.pnpm/@mermaid-js+mermaid-cli@11.12.0_puppeteer@23.11.1/node_modules/@mermaid-js/mermaid-cli/src/node_modules:/home/ubuntu/.local/share/pnpm/global/5/.pnpm/@mermaid-js+mermaid-cli@11.12.0_puppeteer@23.11.1/node_modules/@mermaid-js/mermaid-cli/node_modules:/home/ubuntu/.local/share/pnpm/global/5/.pnpm/@mermaid-js+mermaid-cli@11.12.0_puppeteer@23.11.1/node_modules/@mermaid-js/node_modules:/home/ubuntu/.local/share/pnpm/global/5/.pnpm/@mermaid-js+mermaid-cli@11.12.0_puppeteer@23.11.1/node_modules:/home/ubuntu/.local/share/pnpm/global/5/.pnpm/node_modules"
else
  export NODE_PATH="/home/ubuntu/.local/share/pnpm/global/5/.pnpm/@mermaid-js+mermaid-cli@11.12.0_puppeteer@23.11.1/node_modules/@mermaid-js/mermaid-cli/src/node_modules:/home/ubuntu/.local/share/pnpm/global/5/.pnpm/@mermaid-js+mermaid-cli@11.12.0_puppeteer@23.11.1/node_modules/@mermaid-js/mermaid-cli/node_modules:/home/ubuntu/.local/share/pnpm/global/5/.pnpm/@mermaid-js+mermaid-cli@11.12.0_puppeteer@23.11.1/node_modules/@mermaid-js/node_modules:/home/ubuntu/.local/share/pnpm/global/5/.pnpm/@mermaid-js+mermaid-cli@11.12.0_puppeteer@23.11.1/node_modules:/home/ubuntu/.local/share/pnpm/global/5/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/global/5/.pnpm/@mermaid-js+mermaid-cli@11.12.0_puppeteer@23.11.1/node_modules/@mermaid-js/mermaid-cli/src/cli.js" "$@"
else
  exec node  "$basedir/global/5/.pnpm/@mermaid-js+mermaid-cli@11.12.0_puppeteer@23.11.1/node_modules/@mermaid-js/mermaid-cli/src/cli.js" "$@"
fi
