#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*)
        if command -v cygpath > /dev/null 2>&1; then
            basedir=`cygpath -w "$basedir"`
        fi
    ;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/home/ubuntu/.local/share/pnpm/global/5/.pnpm/puppeteer@23.11.1/node_modules/puppeteer/lib/cjs/puppeteer/node/node_modules:/home/ubuntu/.local/share/pnpm/global/5/.pnpm/puppeteer@23.11.1/node_modules/puppeteer/lib/cjs/puppeteer/node_modules:/home/ubuntu/.local/share/pnpm/global/5/.pnpm/puppeteer@23.11.1/node_modules/puppeteer/lib/cjs/node_modules:/home/ubuntu/.local/share/pnpm/global/5/.pnpm/puppeteer@23.11.1/node_modules/puppeteer/lib/node_modules:/home/ubuntu/.local/share/pnpm/global/5/.pnpm/puppeteer@23.11.1/node_modules/puppeteer/node_modules:/home/ubuntu/.local/share/pnpm/global/5/.pnpm/puppeteer@23.11.1/node_modules:/home/ubuntu/.local/share/pnpm/global/5/.pnpm/node_modules"
else
  export NODE_PATH="/home/ubuntu/.local/share/pnpm/global/5/.pnpm/puppeteer@23.11.1/node_modules/puppeteer/lib/cjs/puppeteer/node/node_modules:/home/ubuntu/.local/share/pnpm/global/5/.pnpm/puppeteer@23.11.1/node_modules/puppeteer/lib/cjs/puppeteer/node_modules:/home/ubuntu/.local/share/pnpm/global/5/.pnpm/puppeteer@23.11.1/node_modules/puppeteer/lib/cjs/node_modules:/home/ubuntu/.local/share/pnpm/global/5/.pnpm/puppeteer@23.11.1/node_modules/puppeteer/lib/node_modules:/home/ubuntu/.local/share/pnpm/global/5/.pnpm/puppeteer@23.11.1/node_modules/puppeteer/node_modules:/home/ubuntu/.local/share/pnpm/global/5/.pnpm/puppeteer@23.11.1/node_modules:/home/ubuntu/.local/share/pnpm/global/5/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/global/5/.pnpm/puppeteer@23.11.1/node_modules/puppeteer/lib/cjs/puppeteer/node/cli.js" "$@"
else
  exec node  "$basedir/global/5/.pnpm/puppeteer@23.11.1/node_modules/puppeteer/lib/cjs/puppeteer/node/cli.js" "$@"
fi
